"""empty message

Revision ID: 09b48d548ca0
Revises: 4965f412853f
Create Date: 2024-10-05 21:10:52.278732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b48d548ca0'
down_revision = '4965f412853f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_names',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_names'))
    )
    op.drop_table('family_name')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_name', sa.String(length=50), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_family_name_family_names'), 'family_names', ['family_name'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_family_name_family_names'), type_='foreignkey')
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('family_name')

    op.create_table('family_name',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_family_name')
    )
    op.drop_table('family_names')
    # ### end Alembic commands ###
