"""empty message

Revision ID: 1d73fa51d486
Revises: f2359b94db7d
Create Date: 2024-10-14 22:21:32.340444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d73fa51d486'
down_revision = 'f2359b94db7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.drop_column('img_str')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_str', mysql.TEXT(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
