"""empty message

Revision ID: 45a4ee7f6695
Revises: 
Create Date: 2024-10-09 11:26:25.422434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a4ee7f6695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('alive', 'deceased', name='status'), nullable=True),
    sa.Column('deceased_at', sa.DateTime(), nullable=True),
    sa.Column('img_str', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=25), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.Column('birth_place', sa.String(length=150), nullable=True),
    sa.Column('birth_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member'))
    )
    op.create_table('moderators',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderators'))
    )
    op.create_table('mod_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('mod_id', sa.String(length=50), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mod_id'], ['moderators.id'], name=op.f('fk_mod_sessions_mod_id_moderators')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mod_sessions'))
    )
    op.create_table('spouse',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('husband_id', sa.String(length=50), nullable=True),
    sa.Column('wife_id', sa.String(length=50), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['husband_id'], ['member.id'], name=op.f('fk_spouse_husband_id_member')),
    sa.ForeignKeyConstraint(['wife_id'], ['member.id'], name=op.f('fk_spouse_wife_id_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spouse'))
    )
    op.create_table('child',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('spouse_id', sa.String(length=50), nullable=True),
    sa.Column('child_type', sa.Enum('son', 'daughter', 'step_son', 'step_daughter', 'adopted_son', 'adopted_daughter', name='childtype'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_child_member_id_member')),
    sa.ForeignKeyConstraint(['spouse_id'], ['spouse.id'], name=op.f('fk_child_spouse_id_spouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_child'))
    )
    op.create_table('other_spouse',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('member_related_to', sa.String(length=50), nullable=True),
    sa.Column('relationship_type', sa.Enum('wife', 'ex_wife', 'husband', 'ex_husband', 'partner', 'ex_partner', 'secondary_wife', name='relationshiptype'), nullable=True),
    sa.Column('spouse_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_other_spouse_member_id_member')),
    sa.ForeignKeyConstraint(['member_related_to'], ['member.id'], name=op.f('fk_other_spouse_member_related_to_member')),
    sa.ForeignKeyConstraint(['spouse_id'], ['spouse.id'], name=op.f('fk_other_spouse_spouse_id_spouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_other_spouse'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_spouse')
    op.drop_table('child')
    op.drop_table('spouse')
    op.drop_table('mod_sessions')
    op.drop_table('moderators')
    op.drop_table('member')
    # ### end Alembic commands ###
