"""empty message

Revision ID: 4965f412853f
Revises: 29bd61d1d4af
Create Date: 2024-10-05 21:09:09.876702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4965f412853f'
down_revision = '29bd61d1d4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_name',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_name'))
    )
    op.create_table('child',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=50), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=False),
    sa.Column('child_type', sa.Enum('son', 'daughter', 'step_son', 'step_daughter', 'adopted_son', 'adopted_daughter', name='childtype'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], name=op.f('fk_child_child_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_child_parent_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_child'))
    )
    op.create_table('relationship',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=False),
    sa.Column('partner_id', sa.String(length=50), nullable=False),
    sa.Column('relationship_type', sa.Enum('wife', 'ex_wife', 'husband', 'ex_husband', 'partner', 'ex_partner', 'secondary_wife', name='relationshiptype'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], name=op.f('fk_relationship_partner_id_users')),
    sa.ForeignKeyConstraint(['person_id'], ['users.id'], name=op.f('fk_relationship_person_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('relationship')
    op.drop_table('child')
    op.drop_table('family_name')
    # ### end Alembic commands ###
