"""empty message

Revision ID: 59383fb1ce84
Revises: 09b48d548ca0
Create Date: 2024-10-05 21:16:30.636512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59383fb1ce84'
down_revision = '09b48d548ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_str', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('img_str')

    # ### end Alembic commands ###
