"""empty message

Revision ID: 5ed568f6ddfc
Revises: cf9a3a5f71ad
Create Date: 2024-10-15 16:57:11.921043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed568f6ddfc'
down_revision = 'cf9a3a5f71ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
