"""empty message

Revision ID: 95549ed392ba
Revises: 9f7a5d3bb5c0
Create Date: 2024-10-28 14:56:41.019899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95549ed392ba'
down_revision = '9f7a5d3bb5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_child_mother_id_spouse'), 'spouse', ['mother_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_child_mother_id_spouse'), type_='foreignkey')
        batch_op.drop_column('mother_id')

    # ### end Alembic commands ###
