"""empty message

Revision ID: b2ed9882fa48
Revises: 59383fb1ce84
Create Date: 2024-10-06 08:13:00.272905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ed9882fa48'
down_revision = '59383fb1ce84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('alive', 'dead', name='status'), nullable=True))
        batch_op.add_column(sa.Column('deceased_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Enum('male', 'female', name='gender'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.Enum('male', 'female', name='gender'),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
        batch_op.drop_column('deceased_at')
        batch_op.drop_column('status')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
