"""empty message

Revision ID: f2359b94db7d
Revises: fb7d9e144813
Create Date: 2024-10-14 22:09:39.368480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2359b94db7d'
down_revision = 'fb7d9e144813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=True),
    sa.Column('img_str', sa.Text(), nullable=True),
    sa.Column('event_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gallery'))
    )
    op.create_table('logo',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('logo_image', sa.Text(), nullable=True),
    sa.Column('logo_title', sa.String(length=50), nullable=True),
    sa.Column('hero_image', sa.Text(), nullable=True),
    sa.Column('story_year', sa.Integer(), nullable=True),
    sa.Column('ancestor_name', sa.String(length=50), nullable=True),
    sa.Column('hero_text', sa.Text(), nullable=True),
    sa.Column('directory_image', sa.Text(), nullable=True),
    sa.Column('clan_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logo')
    op.drop_table('gallery')
    # ### end Alembic commands ###
