"""empty message

Revision ID: f252d853f882
Revises: 95549ed392ba
Create Date: 2024-10-28 15:34:20.641602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f252d853f882'
down_revision = '95549ed392ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_constraint('fk_child_mother_id_spouse', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_child_mother_id_member'), 'member', ['mother_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_child_mother_id_member'), type_='foreignkey')
        batch_op.create_foreign_key('fk_child_mother_id_spouse', 'spouse', ['mother_id'], ['id'])

    # ### end Alembic commands ###
