"""empty message

Revision ID: f96dce357d3c
Revises: 5ed568f6ddfc
Create Date: 2024-10-17 12:30:21.969387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96dce357d3c'
down_revision = '5ed568f6ddfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('alive', 'deceased', name='status'), nullable=True),
    sa.Column('deceased_at', sa.DateTime(), nullable=True),
    sa.Column('img_str', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=25), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.Column('birth_place', sa.String(length=150), nullable=True),
    sa.Column('birth_name', sa.String(length=150), nullable=True),
    sa.Column('story_line', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member'))
    )
    op.create_table('spouse',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('husband_id', sa.String(length=50), nullable=True),
    sa.Column('wife_id', sa.String(length=50), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['husband_id'], ['member.id'], name=op.f('fk_spouse_husband_id_member')),
    sa.ForeignKeyConstraint(['wife_id'], ['member.id'], name=op.f('fk_spouse_wife_id_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spouse'))
    )
    op.create_table('child',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('spouse_id', sa.String(length=50), nullable=True),
    sa.Column('child_type', sa.Enum('son', 'daughter', 'step_son', 'step_daughter', 'adopted_son', 'adopted_daughter', name='childtype'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_child_member_id_member')),
    sa.ForeignKeyConstraint(['spouse_id'], ['spouse.id'], name=op.f('fk_child_spouse_id_spouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_child'))
    )
    op.create_table('other_spouse',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('member_related_to', sa.String(length=50), nullable=True),
    sa.Column('relationship_type', sa.Enum('wife', 'ex_wife', 'husband', 'ex_husband', 'partner', 'ex_partner', 'secondary_wife', name='relationshiptype'), nullable=True),
    sa.Column('spouse_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_other_spouse_member_id_member')),
    sa.ForeignKeyConstraint(['member_related_to'], ['member.id'], name=op.f('fk_other_spouse_member_related_to_member')),
    sa.ForeignKeyConstraint(['spouse_id'], ['spouse.id'], name=op.f('fk_other_spouse_spouse_id_spouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_other_spouse'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_spouse')
    op.drop_table('child')
    op.drop_table('spouse')
    op.drop_table('member')
    # ### end Alembic commands ###
